### PR TITLE
Created OS X app for java

### PR DESCRIPTION
**Pull request by davidcool**
Hello,

I created an OS X app wrapper for the java app so you don't have to go to the command line. I'm using this to interface littleBits and Scratch for 4th and 5th graders and the app makes it more accessible. I just wish I could auto include the JSON file! Anyway, perhaps you'd like to add the app to your repo. Love this project!

Cheers,
David

### CODE REVIEW

**Comment by electronicadivertida** [comment]
I am very happy that the application will be useful, and thank you very much for the contribution

regards

**Comment by davidcool** [comment]
Hello,

I just wanted to share a video I created with my 5th grade class using scratch2littleBits to create a chain reaction. Thanks so much for your work on this project!

https://drive.google.com/file/d/0Bz0mBWhcAp_nVHZxYzlqYWNmcTA/view?usp=sharing

Best,
David

**Comment by electronicadivertida** [comment]
Good evening

Fantastia activity seems a very original,

I'm really glad that my project will be useful

regards

El 10/01/16 a las 18:17, David Cool escribió:
> Hello,
>
> I just wanted to share a video I created with my 5th grade class using 
> scratch2littleBits to create a chain reaction. Thanks so much for your 
> work on this project!
>
> https://drive.google.com/file/d/0Bz0mBWhcAp_nVHZxYzlqYWNmcTA/view?usp=sharing
>
> Best,
> David
>
>
> > On Dec 27, 2015, at 2:21 PM, Electrónica divertida 
> <notifications@github.com> wrote:
> >
> > I am very happy that the application will be useful, and thank you 
> very much for the contribution
> >
> > regards
> >
> > —
> > Reply to this email directly or view it on GitHub 
> <https://github.com/electronicadivertida/scratch2LittleBits/pull/3#issuecomment-167436977>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/electronicadivertida/scratch2LittleBits/pull/3#issuecomment-170372212>.
>

-- 
----
Eduardo González Carpena
C\Juan de la cierva 52
30500 Molina Segura
eduardo@creativa3d.com
www.creativa3d.com
---------
" Este mensaje y sus archivos adjuntos son confidenciales. No está permitida
  su reproducción o distribución sin autorización expresa de Eduardo González
Carpena, Si usted no es el destinatario previsto, cualquier uso, acceso o copia de este
  mensaje queda desautorizado. Si ha recibido este mensaje por error, por
  favor, bórrelo e informe de la recepción a eduardo@creativa3d.com
  Gracias".
-----------

**Comment by davidcool** [comment]
Hello Eduardo,

I’m going to give a talk to our school board of directors about the chain reaction project I worked on using your software. I’d like to mention you and your software in the presentation. Would it be possible to send a photograph of yourself so they could put a face to a name? It would be most appreciated!

Best regards,
David Cool

**Comment by electronicadivertida** [comment]
Goog morning

I added a link from scratch-android-littlebits

https://github.com/electronicadivertida/scratch2LittleBits/tree/master/scratch2LittleBits/scratch2LittleBitsAndroid

El apk
https://github.com/electronicadivertida/scratch2LittleBits/blob/master/scratch2LittleBits/scratch2LittleBitsAndroid/bin/littleBitsBluetooth-release.apk


This mode tests
I hope you find it useful


Best regards

El 15/02/16 a las 18:32, David Cool escribió:
> Hello Eduardo,
>
> I’m going to give a talk to our school board of directors about the 
> chain reaction project I worked on using your software. I’d like to 
> mention you and your software in the presentation. Would it be 
> possible to send a photograph of yourself so they could put a face to 
> a name? It would be most appreciated!
>
> Best regards,
> David Cool
>
>
>
>
> > On Jan 10, 2016, at 5:43 PM, Electrónica divertida 
> <notifications@github.com> wrote:
> >
> > Good evening
> >
> > Fantastia activity seems a very original,
> >
> > I'm really glad that my project will be useful
> >
> > regards
> >
> > El 10/01/16 a las 18:17, David Cool escribió:
> > > Hello,
> > >
> > > I just wanted to share a video I created with my 5th grade class 
> using
> > > scratch2littleBits to create a chain reaction. Thanks so much for 
> your
> > > work on this project!
> > >
> > > 
> https://drive.google.com/file/d/0Bz0mBWhcAp_nVHZxYzlqYWNmcTA/view?usp=sharing
> > >
> > > Best,
> > > David
> > >
> > >
> > > > On Dec 27, 2015, at 2:21 PM, Electrónica divertida
> > > <notifications@github.com> wrote:
> > > >
> > > > I am very happy that the application will be useful, and thank you
> > > very much for the contribution
> > > >
> > > > regards
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/electronicadivertida/scratch2LittleBits/pull/3#issuecomment-167436977>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/electronicadivertida/scratch2LittleBits/pull/3#issuecomment-170372212>.
> > >
> >
> > --
> > ----
> > Eduardo González Carpena
> > C\Juan de la cierva 52
> > 30500 Molina Segura
> > eduardo@creativa3d.com
> > www.creativa3d.com
> > ---------
> > " Este mensaje y sus archivos adjuntos son confidenciales. No está 
> permitida
> > su reproducción o distribución sin autorización expresa de Eduardo 
> González
> > Carpena, Si usted no es el destinatario previsto, cualquier uso, 
> acceso o copia de este
> > mensaje queda desautorizado. Si ha recibido este mensaje por error, por
> > favor, bórrelo e informe de la recepción a eduardo@creativa3d.com
> > Gracias".
> > -----------
> >
> > —
> > Reply to this email directly or view it on GitHub 
> <https://github.com/electronicadivertida/scratch2LittleBits/pull/3#issuecomment-170401250>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/electronicadivertida/scratch2LittleBits/pull/3#issuecomment-184318354>.
>

-- 
----
Eduardo González Carpena
C\Juan de la cierva 52
30500 Molina Segura
eduardo@creativa3d.com
www.creativa3d.com
---------
" Este mensaje y sus archivos adjuntos son confidenciales. No está permitida
  su reproducción o distribución sin autorización expresa de Eduardo González
Carpena, Si usted no es el destinatario previsto, cualquier uso, acceso o copia de este
  mensaje queda desautorizado. Si ha recibido este mensaje por error, por
  favor, bórrelo e informe de la recepción a eduardo@creativa3d.com
  Gracias".
-----------

**Pull request merged**
